### ISSUE TITLE
Error `this.useTaskRunner.toLowerCase is not a function` 

### ISSUE THREAD

**Issue by ghost** [SassDoc/generator-sassdoc-theme#28]
Hello. When trying to create a theme through this tool, I encounter the error `this.use TaskRunner.toLowerCase is not a function'. What could be the problem and how to solve it?

P.S. I don't speak English well and use Google Translate. I'm sorry if the question was distorted by the translator.

![Снимок экрана от 2022-11-09 11-19-38.png](https://user-images.githubusercontent.com/33829769/200777156-c1bd6b79-4962-4830-ba65-faee80b7c2e4.png)

**Comment by pascalduez** [comment]
Hello, 
what version of Yeoman are you using? 
Maybe there's an incompatibility with recent versions, things are getting dusty in here... 
You could try with Yeoman 1.x

**Comment by ghost** [comment]
> Hello, what version of Yeoman are you using? Maybe there's an incompatibility with recent versions, things are getting dusty in here... You could try with Yeoman 1.x

~~Hello, I have the Yeoman 4.3.1 version installed. Now I will try to install the old version.~~ Thanks for the tip.

Don't working with Yo 1.2.1:
```
fs.js:47
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (/usr/local/lib/node_modules/yo/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/yo/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/update-notifier/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by pascalduez** [comment]
Humm now it must be the Node.js version probably. 
Try with lower versions? Maybe 10?
